### ISSUE TITLE
State enum should be a structure well defined

### ISSUE THREAD

**Issue by Koldar** [Koldar/crashc#17]
The code right now define "status" Section field as:

```
enum {
		SECTION_UNEXEC,
		SECTION_EXEC,
		SECTION_DONE,
		SECTION_SIGNAL_DETECTED
} status;
```

This is not ideal because in this way if we have a function that accept a section status as parameter (or return value) we are forced to define its type as "int". It would greatly improve readability if, instead, we could pass something like "section_status_enum".

I suggest chaing the code to:

```
type def enum {
		SECTION_UNEXEC,
		SECTION_EXEC,
		SECTION_DONE,
		SECTION_SIGNAL_DETECTED
} section_status_enum;

typedef struct section {
		...
		section_status_enum status;
		...
} section;
```

**Comment by lorenzonodari** [comment]
Done! Let me know if you think something still needs a little readability tweak!
