### ISSUE TITLE
Tag enhancement

### ISSUE THREAD

**Issue by Koldar** [Koldar/crashc#2]
Tags are simple human readable strings that the programmer can use to uniquely identify tests or suites.

each SUITE and TESTCASE need to accept a list of such strings. Catch uses the syntax "[tag1 tag2 tag3]".
You can think an alternative syntax if you want.
In order to satisfy this task you simply need to associated to each SUITE and TESTCASE a list of those tags

**Comment by Koldar** [comment]
I'm working on this issue right now. I don't know when I will be able to complete it though.

**Comment by lorenzonodari** [comment]
Ok! I'll work on the other issues then. In case you want me to go on and
complete your work just let me know!

**Comment by Koldar** [comment]
Don't worry about it. It's fun project for me as well :)
