### ISSUE TITLE
Protect CrashC #define

### ISSUE THREAD

**Issue by Koldar** [Koldar/crashc#40]
The tested code might define some macros called WHEN or THEN. Every crashc macro should be protected with the following idiom:

```
#ifdef WHEN
#    error "WHEN has been already defined!"
#endif
#define WHEN ...
```

or something like that: in this way, a compilation error will be thrown out (alternatively, we can throw a warning instead of a error=

**Comment by lorenzonodari** [comment]
We should do this for EVERY macro, with particular care for essential macros, like CONTAINABLE_SECTION. We should also prepend _CT_ to the essential macros to avoid collisions with user code as much as possible.

**Comment by Koldar** [comment]
We should protect every macro, since potentially every macro may be overridden by the user and crashC needs to intercept that. I suggest to prepend every macro with "CT_". What should be have to throw? an error via "#error" or a warning via "#warning"? I think "#error" is better because we can't know what a modified macro might cause to the internals of crashc.

**Comment by lorenzonodari** [comment]
I agree, we should throw a compilation error, as a warning would probably be ignored and the code would result **very** broken. As per the `CT_` prefix, you want to add it even to user-facing macros, like `THEN`, `TESTCASE`, etc..? That would be a bit annoying maybe, and i think that there will be more situations where those macros are not defined by tested code rathen that ones in which they will be defined, so prepending the prefix on those would add bloat most of the time. Am i wrong?

**Comment by Koldar** [comment]
You're right, `TESTCASE` and company shouldn't have the prefix `CT_`. However, they should still be guarded as well
