### ISSUE TITLE
Adopt a unified code style

### ISSUE THREAD

**Issue by lorenzonodari** [Koldar/crashc#44]
At the moment the whole code base does not use a single codestyle.
This is clearly very bad, so we need to refactor the code in order to adopt a unified code style

**Comment by lorenzonodari** [comment]
In particular:
- Use snake case for every identifier e.g: `i_am_an_identifier`
- Postpend "_t" to typedefs
- Convert pointer types definition style from `type *` to `type*`

**Comment by lorenzonodari** [comment]
We should also refactor every CrashC macro in order not to use snake case names
e.g: `REG_TEST` into `REGTEST` etc

**Comment by Koldar** [comment]
As per @lorenzonodari request, every enum value in crash C should be prefixed with "CT_" string. So, for example we have `CT_SECTION_UNVISITED` instead of `SECTION_UNVISITED`

**Comment by Koldar** [comment]
@lorenzonodari asked if the file `typedef.h` should be removed from the project, since it contains only typedef of callbacks. Care to argument more deeply your position?

**Comment by lorenzonodari** [comment]
There are no strong reasons, just a few minor points:
* First of all, now that we don't have problems with cyclic dependencies anymore thanks to the new structures codestyle, the file feels a bit unecessary to me, as every typedef contained there might as well fit in another module without any problem
* Secondly, distributing every typedef in its corresponding module instead of a generic module like typedefs.h __might__ help a developer to understand the reasons behind an inclusion at first glance.
What i mean by this is: suppose we need to include `typedefs.h` __just__ because of a typedef, suppose `ct_assert_c`. The fact that we need that typedef implies that we are working with something related to assertions, so if the callback type was defined inside `assertions.h`, including that file instead of the other would maybe underline this dependency a bit better.

I hope i could explaing what i mean!
As i said, these two motivations are surely not "game-changing", so keeping the file is not a problem to me at all, these ere just a few considerations i had thought about, let me know what you think!

**Comment by Koldar** [comment]
But what about modules that needs 2 of them? Let's say module `A` needs 2 typedef, `typedef1` and `typedef2`. But `typedef1` is defined in module `B` and `typedef2` is defined in module `C`: we just needed typedefs, but we are forced to include 2 entire modules!
I think this is a trade off.

**Comment by Koldar** [comment]
I think we should keep the file. General purposes typedefs (such as function callback types) should be here. The only overhead is to declare the types inside the callback parameters but, aside from that, I don't see drawbacks. The argument that it might help the developer appears too small to me.
