### ISSUE TITLE
Dynamic main test

### ISSUE THREAD

**Issue by Koldar** [Koldar/crashc#5]
TESTS and BEGIN macro should contain some code to understand some simple command line parameters.
You should use `getopt` function to retrieve that commands. These are the commands I've thought useful:

1.  --run-only: this option requires a list of tags. Only the SUITE and TESTCASE having at least one of those tags will be run. The other will be skipped; If no list of tags is provided, the list to consider is "now";
2.  --exclude: this option requires a list of tags. If a SUITE of TESTCASE have at least one of those tags they won't be executed. if a SUITE or TESTCASE have both a --run-only or --exclude tag, `exclude` has the precedence;
3. --run-suites: like --run-only but checks only SUITES;
4. --run-testcases: like --run-only but checks only TESTCASE;
5. --exclude-suites: like --exclude but checks only SUITES;
6. --exclude-testcases: like --exclude but checks only TESTCASE;

**Comment by Koldar** [comment]
Can I implement this feature?

**Comment by lorenzonodari** [comment]
Sure, you can take this task!

**Comment by Koldar** [comment]
perfect!
