### ISSUE TITLE
Signal handler

### ISSUE THREAD

**Issue by Koldar** [Koldar/crashc#6]
The tested software can go in segmentation fault or receive some other signals. The crashc should allow you to deal with it by aborting the current test, marking with something more than failed (like "crashed") and keep the test going.

You can do that with these links:

- https://stackoverflow.com/questions/3151779/how-its-better-to-invoke-gdb-from-program-to-print-its-stacktrace?noredirect=1&lq=1;
- https://stackoverflow.com/a/10203062/1887602;

These link might be platform or compiler dependent (the 2nd for sure!)

**Comment by Koldar** [comment]
When I was retrieving information for this task, I came across the funciton sigaction: maybe you can register a new handler for a particular signal. If there was no handler for a partocular signal, you can register a crashC one, otherwise you can do nothing.

link: https://stackoverflow.com/questions/9495113/how-to-get-the-handlers-name-address-for-some-signals-e-g-sigint-in-postgres

**Comment by lorenzonodari** [comment]
Ciao Massimo,

stavo appunto per scriverti a riguardo! Ieri sera ho letto la parte del
manuale della GNU C Library riguardante la gestione dei segnali ho letto
anche io della funzione, e infatti ho avuto un'idea simile!
Verificare se l'utente registra un suo handler temo sia impossibile, in
quanto andrebbe fatto alla fine del codice per il suo test, e di
conseguenza la registrazione avverebbe dopo l'effettiva esecuzione del
test, diventato pertanto inutile.
Se tuttavia noi registrassimo a prescindere il nostro handler all'inizio
della funzione di test potremmo ottenere una soluzione. Infatti se l'utente
decide di registrare un handler per il segnale, esso sovrascriverebbe
semplicemente quello
di CrashC, fornendo all'utente il risultato desiderato. In caso invece
l'utente non registri nulla, avremmo il nostro handler pronto a gestire
eventuali situazioni di errore!
Con questo approccio potremmo quindi infine verificare, al termine del
test, se e' avvenuta o meno una effettiva modifica dell'handler e agire di
conseguenza!

Pensi possa essere un approccio corretto? Perche' in tal caso procedo e
inizio a mettermi al lavoro sul codice!

**Comment by lorenzonodari** [comment]
Ah dimenticavo, unico problema nell'utilizzo di sigaction e' che e' POSIX
compliant ma non ISO C compliant da quanto ho capito.
In caso preferissi non utilizzare codice portabile unicamente in ambito
POSIX in realta' penso che si possa ottenere lo stesso risultato
(riferendomi alla mia proposta di prima) utilizzando la piu' semplice
funzione signal().


2017-07-04 13:43 GMT+02:00 Lorenzo Nodari <lorenzo.nodari.it@ieee.org>:

**Comment by Koldar** [comment]
Mmm... being sigaction a POSIX standard one might want to use `signal` instead. How can you detect if someone altered the signal handling (at the end of the test)?

**Comment by lorenzonodari** [comment]
Ok, i'll stick to signal() then! I think you should be able to detect if comeone altered the signal handling by checking the return value of a call to signal(). In fact, its prototype is:

`sighandler_t signal (int signum, sighandler_t action)`

and, reading from the official GNU C Library reference:
> The signal function returns the action that was previously in effect for the specified signum.

By comparing the return value of the signal function we can then check whether or not our handler was changed.

**Comment by Koldar** [comment]
Perfect! I didn't read `signal` documentation, but I think we have everything we need from the simple `signal` function! Great work!

**Comment by Koldar** [comment]
Please commit the associated code. I'll research a solution as soon as I have spare time

**Comment by Koldar** [comment]
Given the following scenario:
```
TESTCASE("", "") {
    //do stuff 1
    WHEN("", "") {
        //dostuff 2
    }
    //do stuff3
}
```

if *dostuff2* does not create a signal then we have only one loop of the testcase. Otherwise we have 2 loops (thereby dostuff1 is called twice). This is counterinuitive becuase the presence of the signal changes the number of tests executed!

**Comment by Koldar** [comment]
As proposed by @lorenzonodari we should mark the entire testcase as "signal detected" and move on to the next testcase in the suite.
Proposal accepted
