### ISSUE TITLE
is the field testcase_snapshot in ct_test_report_t always different than null?

### ISSUE THREAD

**Issue by Koldar** [Koldar/crashc#66]
Or maybe there are some scenarios where such field can be null?

care to solve this question for me?

**Comment by lorenzonodari** [comment]
For how the code works at the moment, there is no such scenario.
The pointer is initialized inside the ct_init_test_report function to the value passed as an argument and never changed throughout the life of the structure.

**Comment by Koldar** [comment]
Ok, so it can never be NULL. I've asked this because I've created a documentation alias (i.e. a macro) called "@notnull" to put to any variables/fields which is always not null. 

FYI: If you happen to create new function which needs to be documented, either add a todo "TODO doc" to remember us to document the function or document the function in docxygen yourself. There are plenty of examples out there.
If you need something, don't hesitate ask me!
