### ISSUE TITLE
Segmentation fault when asserting

### ISSUE THREAD

**Issue by Koldar** [Koldar/crashc#71]
Given the following test:
```
#include <stdio.h>
#include "crashC.h"

TESTS_START
REG_SUITE(0);
TESTS_END

TESTSUITE(0) {
	int sum = 0;
	sum += 1;
	ASSERT(sum >= 0 && sum <= 10);
}
```

The framework goes into segmentation fault. It seems a problem when asserting: in particular it seems that `(model)->current_snapshot` is `NULL`

**Comment by Koldar** [comment]
I've already created on the master a test_issue71.c containing the code going in error

**Comment by Koldar** [comment]
remember to estimate a time, so our burndown table will be up to date  ;)

**Comment by lorenzonodari** [comment]
I marked the issue as wontfix as we realized that the framework **at the moment** cannot support out-of-testcase assertions. We will though improve the framework in a next release in order to let this be possible.
