### ISSUE TITLE
Mark the documentation of ct_test_report_t with adoxygen alias "notnull"

### ISSUE THREAD

**Issue by Koldar** [Koldar/crashc#72]

**Comment by lorenzonodari** [comment]
I don't think i understand this issue, what is the point of marking a structure with `@notnull`?

**Comment by Koldar** [comment]
By adding in the documentation the alias `@notnull` in the documentation it is automatically added the sentence "This field cannot be null". This information is useful for the user

**Comment by Koldar** [comment]
I think we should keep the file. General purposes typedefs (such as function callback types) should be here. The only overhead is to declare the types inside the callback parameters but, aside from that, I don't see drawbacks
